# Site settings
title: saviourcode
email: SourabhJaywant.Choure@UTDallas.edu
description: > # this means to ignore newlines until "baseurl:"
  Test App hosted on Netlify and GitHub Repo
  The description is short and to the point.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: sjchoure
github_username:  saviourcode

# Build settings
markdown: kramdown
